### PR TITLE
Rewrite PACKAGE_ASYNC to fix data race, also implement async_getdir correctly

### LINKED ISSUE #514: driver crashed when using async package
(gdb) bt
#0  0x00007fe5d7f17c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fe5d7f1b028 in __GI_abort () at abort.c:89
#2  0x00007fe5d7f10bf6 in __assert_fail_base (fmt=0x7fe5d8065058 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fe5d87d8a3c "mutex->__data.__owner == 0", file=file@entry=0x7fe5d87d8a08 "../nptl/pthread_mutex_lock.c", line=line@entry=80, function=function@entry=0x7fe5d87d8b40 <__PRETTY_FUNCTION__.8524> "__pthread_mutex_lock") at assert.c:92
#3  0x00007fe5d7f10ca2 in __GI___assert_fail (assertion=0x7fe5d87d8a3c "mutex->__data.__owner == 0", file=0x7fe5d87d8a08 "../nptl/pthread_mutex_lock.c", line=80, function=0x7fe5d87d8b40 <__PRETTY_FUNCTION__.8524> "__pthread_mutex_lock") at assert.c:101
#4  0x00007fe5d87d04fc in __GI___pthread_mutex_lock (mutex=0x7fe5d66000c0) at ../nptl/pthread_mutex_lock.c:80
#5  0x00007fe5d8c2fb8c in thread_func (mydata=<optimized out>) at packages/async/async.cc:100
#6  0x00007fe5d87ce184 in start_thread (arg=0x7fe5d59ff700) at pthread_create.c:312
#7  0x00007fe5d7fdf03d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) bt
#0  0x00007fe5d7f17c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fe5d7f1b028 in __GI_abort () at abort.c:89
#2  0x00007fe5d7f10bf6 in __assert_fail_base (fmt=0x7fe5d8065058 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fe5d87d8a3c "mutex->__data.__owner == 0", file=file@entry=0x7fe5d87d8a08 "../nptl/pthread_mutex_lock.c", line=line@entry=80, function=function@entry=0x7fe5d87d8b40 <__PRETTY_FUNCTION__.8524> "__pthread_mutex_lock") at assert.c:92
#3  0x00007fe5d7f10ca2 in __GI___assert_fail (assertion=0x7fe5d87d8a3c "mutex->__data.__owner == 0", file=0x7fe5d87d8a08 "../nptl/pthread_mutex_lock.c", line=80, function=0x7fe5d87d8b40 <__PRETTY_FUNCTION__.8524> "__pthread_mutex_lock") at assert.c:101
#4  0x00007fe5d87d04fc in __GI___pthread_mutex_lock (mutex=0x7fe5d66000c0) at ../nptl/pthread_mutex_lock.c:80
#5  0x00007fe5d8c2fb8c in thread_func (mydata=<optimized out>) at packages/async/async.cc:100
#6  0x00007fe5d87ce184 in start_thread (arg=0x7fe5d59ff700) at pthread_create.c:312
#7  0x00007fe5d7fdf03d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) c
Continuing.
Program received signal SIGABRT, Aborted.
0x00007fe5d7f17c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      in ../nptl/sysdeps/unix/sysv/linux/raise.c
(gdb) bt
#0  0x00007fe5d7f17c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fe5d7f1b028 in __GI_abort () at abort.c:89
#2  0x00007fe5d8c866b4 in fatal (fmt=fmt@entry=0x7fe5d8d79ef5 "SIGABRT: Aborted") at vm/internal/simulate.cc:1701
#3  0x00007fe5d8ce7cb2 in attempt_shutdown(int) [clone .53112] (sig=<optimized out>) at main.cc:310
#4  <signal handler called>
#5  0x00007fe5d7f17c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#6  0x00007fe5d7f1b028 in __GI_abort () at abort.c:89
#7  0x00007fe5d7f10bf6 in __assert_fail_base (fmt=0x7fe5d8065058 "%s%s%s:%u: %s% sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fe5d87d8a3c "mutex->_ _data.__owner == 0", file=file@entry=0x7fe5d87d8a08 "../nptl/pthread_mutex_lock. c", line=line@entry=80, function=function@entry=0x7fe5d87d8b40 <__PRETTY_FUNCTIO N__.8524> "__pthread_mutex_lock") at assert.c:92
#8  0x00007fe5d7f10ca2 in __GI___assert_fail (assertion=0x7fe5d87d8a3c "mutex->__data.__owner == 0", file=0x7fe5d87d8a08 "../nptl/pthread_mutex_lock.c", line=80 , function=0x7fe5d87d8b40 <__PRETTY_FUNCTION__.8524> "__pthread_mutex_lock") at  assert.c:101
#9  0x00007fe5d87d04fc in __GI___pthread_mutex_lock (mutex=0x7fe5d66000c0) at ../nptl/pthread_mutex_lock.c:80
#10 0x00007fe5d8c2fb8c in thread_func (mydata=<optimized out>) at packages/async/async.cc:100
#11 0x00007fe5d87ce184 in start_thread (arg=0x7fe5d59ff700) at pthread_create.c:312
#12 0x00007fe5d7fdf03d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

### LINKED ISSUE #611: PACKAGE_ASYNC 编译失败
环境是Debian9 arm64架构，去除该包可正常编译完成。
```
[  1%] Built target libtelnet
[  1%] Built target make_options_defs
[  2%] Built target build_applies
[  4%] Built target make_func
[  5%] Built target portbind
[  9%] Built target crypt
[ 13%] Built target autogen
[ 14%] Built target package_math
[ 16%] Built target package_compress
[ 16%] Built target package_pcre
[ 15%] Built target package_crypto
[ 17%] Built target package_contrib
[ 18%] Built target package_db
[ 31%] Built target package_core
[ 31%] Built target package_parser
[ 33%] Built target package_ops
[ 34%] Built target package_mudlib_stats
[ 44%] Built target package_sha1
[ 66%] Built target websockets
[ 67%] Built target package_matrix
[ 69%] Built target package_sockets
[ 70%] Built target package_trim
[ 71%] Built target package_uids
[ 74%] Building CXX object src/packages/async/CMakeFiles/package_async.dir/async.cc.o
[ 74%] Built target package_develop
/root/fluffos/src/packages/async/async.cc: In function ‘void* getdirthread(request*)’:
/root/fluffos/src/packages/async/async.cc:301:22: error: ‘SYS_getdents’ was not declared in this scope
   int size = syscall(SYS_getdents, fd, req->buf, req->size);
                      ^~~~~~~~~~~~
src/packages/async/CMakeFiles/package_async.dir/build.make:62: recipe for target 'src/packages/async/CMakeFiles/package_async.dir/async.cc.o' failed
make[2]: *** [src/packages/async/CMakeFiles/package_async.dir/async.cc.o] Error 1
CMakeFiles/Makefile2:1060: recipe for target 'src/packages/async/CMakeFiles/package_async.dir/all' failed
make[1]: *** [src/packages/async/CMakeFiles/package_async.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by thefallentree**
fix #514 
fix #611

### CODE REVIEW

**Comment by thefallentree** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/fluffos/fluffos/pullRequest?prid=5214413&bid=17098056)

File: src/packages/async/async.cc [hunk 1]
```diff
@@ -2,18 +2,32 @@
...
 #include "packages/async/async.h"
 
+#include <chrono>
+#include <deque>
+#include <mutex>
+#include <thread>
+
+#if HAVE_DIRENT_H
 #include <dirent.h>
+#define NAMLEN(dirent) strlen((dirent)->d_name)
```
Comment (thefallentree) [inline src/packages/async/async.cc]: Codacy Issue found: [Does not handle strings that are not \0-terminated; if given one it may perform an over-read (it could cause a crash if unprotected) (CWE-126).  ](https://app.codacy.com/gh/fluffos/fluffos/pullRequest?prid=5214413)

File: src/packages/async/async.cc [hunk 2]
```diff
@@ -557,9 +455,8 @@ void f_async_write() {
 
 #ifdef F_ASYNC_GETDIR
 void f_async_getdir() {
-  function_to_call_t *cb = get_cb();
-  process_efun_callback(1, cb, F_ASYNC_READ);
-  cb->f.fp->hdr.ref++;
+  auto *cb = new function_to_call_t;
+  process_efun_callback(1, cb, F_ASYNC_GETDIR);
```
Comment (thefallentree) [inline src/packages/async/async.cc]: Codacy Issue found: [Skipping configuration 'F_ASYNC_GETDIR' since the value of 'F_ASYNC_GETDIR' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.](https://app.codacy.com/gh/fluffos/fluffos/pullRequest?prid=5214413)

**Comment by thefallentree** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/fluffos/fluffos/pullRequest?prid=5214413&bid=17098056)

File: src/packages/async/async.cc [hunk 3]
```diff
@@ -557,9 +453,8 @@ void f_async_write() {
...
```
Comment (thefallentree) [inline src/packages/async/async.cc]: Codacy Issue found: [Skipping configuration 'F_ASYNC_GETDIR' since the value of 'F_ASYNC_GETDIR' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.](https://app.codacy.com/gh/fluffos/fluffos/pullRequest?prid=5214413)

**Comment by thefallentree** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/fluffos/fluffos/pullRequest?prid=5214413&bid=17098056)

File: src/packages/async/async.cc [hunk 4]
```diff
@@ -557,9 +452,8 @@ void f_async_write() {
...
```
Comment (thefallentree) [inline src/packages/async/async.cc]: Codacy Issue found: [Skipping configuration 'F_ASYNC_GETDIR' since the value of 'F_ASYNC_GETDIR' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.](https://app.codacy.com/gh/fluffos/fluffos/pullRequest?prid=5214413)
