### PR TITLE
fix: avoid corruption after using test_load

### LINKED ISSUE #843: Crasher when testing load of something already loaded
If you run the `test_load` function to check if a file can load or not, on a file that is already loaded, then it crashes. 
 It can be tested on Lil/testsuite by doing `eval return test_load(base_name(this_object()));`

For now, it can be avoided with a simul_efun like this:
```c
int test_load(string filename){
  if(filename && find_object(filename)) error("test_load called on already loaded "+filename);
  return efun::test_load(filename);
}
```

### PR DESCRIPTION
**Pull request by hluaces**
When using `test_load` on a loaded object the object list ends up corrupted. The details are obscure, but doing this reproduces the error:

1. Load any object in memory. Check that both `find_object()` and `children()` return the single existing object
2. Run `test_load` on the object. At this point `find_object()` will probably return `0` (sometimes it doesn't)
3. Destroy and use `load_object()` again. `children()` will now return an array with two duplicates of the same object or, sometimes, a `0` and the existing copy of the object

In some instances i've seen different objects returned by `children()` than the one being passed as path (this usually happened with clones).

This PR tries to work around it. I've also reverted #843 because I believe this PR fixes the underlying cause for the issue, not just the symptom.

All credit goes to Zoilder (one of the developers on our mud) that happened to fix this a long time ago. We're just sending these fixes upstream since we're starting to update our outdated driver.

Please let me know if there's anything I should change in the PR. I've tried to add a proper test for this, but I don't know if that's the location you're expecting for it.

### CODE REVIEW

File: testsuite/single/tests/crasher/1063-aux.c [hunk 1]
```diff
@@ -0,0 +1,2 @@
+void create() {
```
Comment (hluaces) [inline testsuite/single/tests/crasher/1063-aux.c:1]: This test does nothing by it's own, but I need a different object I can load/destroy from the `1063.c` file.

**Review by thefallentree — APPROVED** [review]
